"""Import legacy CSV files generated by transform_legacy into ERPNext.

Run with bench, for example:
bench --site SITE execute asset_mgmt.import.import_csv.run --kwargs '{"output_dir": "/tmp/asset-import-full"}'
"""

from __future__ import annotations

import csv
import os
from datetime import datetime
from typing import Any

import frappe


COMPANY = "Asset Management"
IMPORT_ORDER = [
	("Cost Center", "cost_center.csv"),
	("Location", "location.csv"),
	("Asset Category", "asset_category.csv"),
	("Item", "item.csv"),
	("Supplier", "supplier.csv"),
	("Asset", "asset.csv"),
]


def run(output_dir, skip_masters=False):
	"""Import generated CSV files from output_dir into the current site."""
	base = os.path.expanduser(output_dir)
	order = IMPORT_ORDER[5:] if skip_masters else IMPORT_ORDER

	results = {}
	errors = []
	for doctype, filename in order:
		path = os.path.join(base, filename)
		if not os.path.exists(path):
			errors.append(f"Missing file: {path}")
			continue
		results[doctype] = _import_file(doctype, path, errors)

	return {"results": results, "errors": errors}


def _import_file(doctype: str, path: str, errors: list[str]) -> dict[str, int]:
	imported = skipped = failed = 0
	batch_size = 100 if doctype == "Asset" else 1

	for row in _rows_for(path):
		try:
			payload = _prepare_row(doctype, row)
			if _exists(doctype, payload):
				skipped += 1
				continue

			doc = frappe.get_doc({"doctype": doctype, **payload})
			doc.insert(ignore_permissions=True)
			imported += 1

			if imported % batch_size == 0:
				frappe.db.commit()
		except Exception as exc:
			frappe.db.rollback()
			failed += 1
			if failed <= 5:
				errors.append(f"{doctype} row failed ({row.get('asset_name') or row.get('item_code') or row}): {exc}")

	if imported % batch_size != 0:
		frappe.db.commit()

	return {"imported": imported, "skipped": skipped, "failed": failed}


def _rows_for(filename: str):
	with open(filename, newline="", encoding="utf-8") as handle:
		for row in csv.DictReader(handle):
			yield {key: (value.strip() if isinstance(value, str) else value) for key, value in row.items()}


def _prepare_row(doctype: str, row: dict[str, Any]) -> dict[str, Any]:
	meta = frappe.get_meta(doctype)
	payload = {}

	for field in meta.fields:
		fieldname = field.fieldname
		if fieldname not in row:
			continue
		value = row[fieldname]
		if value in (None, ""):
			continue
		payload[fieldname] = _convert(value, field)

	if doctype == "Cost Center":
		payload.setdefault("company", COMPANY)
		payload.setdefault("is_group", 0)

	if doctype == "Asset Category":
		payload["accounts"] = _asset_category_accounts(row)

	if doctype == "Asset":
		payload["company"] = COMPANY
		payload["calculate_depreciation"] = 0
		payload = _resolve_asset_links(payload)

	return payload


def _asset_category_accounts(row: dict[str, Any]) -> list[dict[str, Any]]:
	account_fields = [
		"fixed_asset_account",
		"accumulated_depreciation_account",
		"depreciation_expense_account",
	]
	accounts = []
	for fieldname in account_fields:
		value = row.get(fieldname)
		if value:
			accounts.append({"company_name": COMPANY, fieldname: value})
	return accounts


def _resolve_asset_links(payload: dict[str, Any]) -> dict[str, Any]:
	cost_center = payload.get("cost_center")
	if cost_center and not frappe.db.exists("Cost Center", cost_center):
		suffixed = f"{cost_center} - AM"
		if frappe.db.exists("Cost Center", suffixed):
			payload["cost_center"] = suffixed

	supplier = payload.get("supplier")
	if supplier and not frappe.db.exists("Supplier", supplier):
		payload.pop("supplier", None)

	return payload


def _exists(doctype: str, payload: dict[str, Any]) -> bool:
	if doctype == "Cost Center":
		name = payload.get("cost_center_name")
		if name and frappe.db.exists("Cost Center", {"cost_center_name": name, "company": COMPANY}):
			return True
		if name and frappe.db.exists("Cost Center", f"{name} - AM"):
			return True

	if doctype == "Location":
		name = payload.get("location_name")
		if name and frappe.db.exists("Location", name):
			return True

	if doctype == "Asset Category":
		name = payload.get("asset_category_name")
		if name and frappe.db.exists("Asset Category", name):
			return True

	if doctype == "Item":
		code = payload.get("item_code")
		if code and frappe.db.exists("Item", code):
			return True

	if doctype == "Supplier":
		name = payload.get("supplier_name")
		if name and frappe.db.exists("Supplier", name):
			return True

	if doctype == "Asset":
		for fieldname in ("legacy_asset_code", "asset_tag"):
			value = payload.get(fieldname)
			if value and frappe.db.exists("Asset", {fieldname: value, "company": COMPANY}):
				return True

	return False


def _convert(value: Any, field) -> Any:
	fieldtype = field.fieldtype

	if fieldtype == "Check":
		return 1 if str(value).strip().lower() in {"1", "true", "yes", "y"} else 0

	if fieldtype in {"Int", "Long Int"}:
		return int(float(str(value).replace(",", "")))

	if fieldtype in {"Float", "Currency", "Percent"}:
		return float(str(value).replace(",", ""))

	if fieldtype == "Date":
		text = str(value).strip()
		for date_format in ("%Y-%m-%d", "%d/%m/%Y", "%d-%b-%y"):
			try:
				return datetime.strptime(text, date_format).date()
			except ValueError:
				continue
		return text

	return value
